#!/usr/bin/env node
// @generated by mcporter@0.7.3 on 2026-03-31T01:14:08.103Z. DO NOT EDIT.
import { Command } from 'commander';
import { createRuntime, createServerProxy } from 'mcporter';
import { createCallResult } from 'mcporter';

const embeddedServer = {
  "name": "dingtalk-docs",
  "description": "dingtalk-mcp-4fd7808438dcd2709bc28c6ce2c6ac811b94b48a2674dbe6e077910f4399b1cb",
  "command": {
    "kind": "http",
    "url": "https://mcp-gw.dingtalk.com/server/4fd7808438dcd2709bc28c6ce2c6ac811b94b48a2674dbe6e077910f4399b1cb?key=fa8500322e305000e73af7b9b3768eba",
    "headers": {
      "accept": "application/json, text/event-stream"
    }
  },
  "source": {
    "kind": "local",
    "path": "/root/.openclaw/workspace/config/mcporter.json"
  },
  "sources": [
    {
      "kind": "local",
      "path": "/root/.openclaw/workspace/config/mcporter.json"
    }
  ]
} as const;
const embeddedSchemas = {
  "list_accessible_documents": {
    "type": "object",
    "properties": {
      "keyword": {
        "type": "string",
        "title": "keyword",
        "description": "keyword"
      }
    },
    "required": [],
    "title": "root",
    "description": "root"
  },
  "get_document_content_by_url": {
    "type": "object",
    "properties": {
      "docUrl": {
        "type": "string",
        "title": "文档链接",
        "description": "用于定位目标文档的钉钉文档访问链接。与 dentryUuid 二选一必填。 格式：https://alidocs.dingtalk.com/i/nodes/{dentryUuid} 或 https://docs.dingtalk.com/i/nodes/{dentryUuid}"
      },
      "dentryUuid": {
        "type": "string",
        "title": "文档id",
        "description": "文档的唯一标识，用于定位目标文档。与 docUrl 二选一必填。 规则：32 位字母数字字符串 可用于拼接生成链接：https://alidocs.dingtalk.com/i/nodes/{dentryUuid}"
      }
    },
    "required": [],
    "title": "入参",
    "description": "入参"
  },
  "get_my_docs_root_dentry_uuid": {
    "type": "object",
    "properties": {},
    "required": [],
    "title": "请求",
    "description": "请求"
  },
  "write_content_to_document": {
    "type": "object",
    "properties": {
      "content": {
        "type": "string",
        "title": "要写入的内容",
        "description": "要写入的内容，支持markdown格式"
      },
      "updateType": {
        "type": "number",
        "title": "更新方式",
        "description": "0表示完全覆盖已有内容；1表示新增段落续写"
      },
      "targetDentryUuid": {
        "type": "string",
        "title": "要写入的文档唯一ID",
        "description": "目标文档的唯一id。一般为dentryUuid"
      }
    },
    "required": [
      "targetDentryUuid",
      "content",
      "updateType"
    ],
    "title": "入参",
    "description": "入参"
  },
  "create_doc_under_node": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "title": "文档名称",
        "description": "需要创建的文档名称"
      },
      "parentDentryUuid": {
        "type": "string",
        "title": "父节点ID",
        "description": "需要创建的父节点ID。可使用 dentryUuid /docId（如来自创建文档、搜索有权限文档等操作的结果）"
      }
    },
    "required": [
      "parentDentryUuid",
      "name"
    ],
    "title": "入参",
    "description": "入参"
  },
  "create_dentry_under_node": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "title": "name",
        "description": "文件夹名称"
      },
      "accessType": {
        "type": "string",
        "title": "accessType",
        "description": "新增的节点类型，枚举类型：0:文档；1:表格；2:PPT；3:白板；6:脑图；7:多维表；9:视频；10:图片；13:文件夹；14:PDF；99:其他文件"
      },
      "parentDentryUuid": {
        "type": "string",
        "title": "parentDentryUuid",
        "description": "父节点ID"
      }
    },
    "required": [
      "parentDentryUuid",
      "name",
      "accessType"
    ],
    "title": "入参",
    "description": "入参"
  }
} as const;
const embeddedName = "dingtalk-docs";
const embeddedDescription = "dingtalk-mcp-4fd7808438dcd2709bc28c6ce2c6ac811b94b48a2674dbe6e077910f4399b1cb";
const generatorInfo = "Generated by mcporter@0.7.3 — https://github.com/steipete/mcporter";
const generatorTools = [
  {
    "name": "list-accessible-documents",
    "description": "根据关键词，查询员工有权限访问的所有文档列表，返回文档uuid、文档标题、类型和最后更新时间。",
    "usage": "list-accessible-documents [--keyword <keyword>] [--raw <json>]",
    "flags": "[--keyword <keyword>] [--raw <json>]"
  },
  {
    "name": "get-document-content-by-url",
    "description": "根据钉钉文档链接（docUrl）或文档ID（dentryUuid）获取文档内容，并以 Markdown 返回。目前仅支持钉钉在线文档。文档链接：https://alidocs.dingtalk.com/i/nodes/{dentryUuid}。dentryUuid 为32位字母数字串。仅限用户对文档具备“下载权限”时可获取，不支持跨组织查询。docUrl 与 dentryUuid 二选一必填",
    "usage": "get-document-content-by-url [--doc-url <doc-url>] [--dentry-uuid <dentry-uuid>] [--raw <json>]",
    "flags": "[--doc-url <doc-url>] [--dentry-uuid <dentry-uuid>] [--raw <json>]"
  },
  {
    "name": "get-my-docs-root-dentry-uuid",
    "description": "获取当前用户“我的文档”空间的根目录节点 ID（rootDentryUuid），该 ID 可作为父节点用于创建新文档或文件夹。返回结果为一个唯一的字符串标识，仅限用户本人访问，适用于初始化文档操作、构建个人文档树等场景",
    "usage": "get-my-docs-root-dentry-uuid [--raw <json>]",
    "flags": "[--raw <json>]"
  },
  {
    "name": "write-content-to-document",
    "description": "将指定文本内容写入目标文档，支持两种模式：覆盖写入（清空原文档内容后写入）或续写（在文档末尾新增段落）。需提供文档唯一标识（文档ID）和写入模式。操作受文档权限控制，仅当调用者拥有编辑权限时生效。适用于自动化报告生成、日志记录、协作内容更新等场景。",
    "usage": "write-content-to-document --content <content> --update-type <update-type:number> --target-dentry-uuid <target-dentry-uuid> [--raw <json>]",
    "flags": "--content <content> --update-type <update-type:number> --target-dentry-uuid <target-dentry-uuid> [--raw <json>]"
  },
  {
    "name": "create-doc-under-node",
    "description": "在指定父节点（通过 dentryUuid 标识，如文件夹、文档、或“我的文档”根目录）下创建一篇新的在线文档，需提供文档名称。成功后返回新文档的详细信息，包括文档 ID（dentryUuid）、标题、创建时间、访问链接等。操作受权限控制，仅当调用者对父节点有写入权限时可成功创建。",
    "usage": "create-doc-under-node --name <name> --parent-dentry-uuid <parent-dentry-uuid> [--raw <json>]",
    "flags": "--name <name> --parent-dentry-uuid <parent-dentry-uuid> [--raw <json>]"
  },
  {
    "name": "create-dentry-under-node",
    "description": "在指定钉钉文档节点下，创建新节点，新增的节点类型有文件夹、PDF、PPT、图片、视频、多维表、脑图、白板、表格、文档",
    "usage": "create-dentry-under-node --name <name> --access-type <access-type> --parent-dentry-uuid <parent-dentry-uuid> [--raw <json>]",
    "flags": "--name <name> --access-type <access-type> --parent-dentry-uuid <parent-dentry-uuid> [--raw <json>]"
  }
] as const;
const embeddedMetadata = {
  "schemaVersion": 1,
  "generatedAt": "2026-03-31T01:14:08.103Z",
  "generator": {
    "name": "mcporter",
    "version": "0.7.3"
  },
  "server": {
    "name": "dingtalk-docs",
    "source": {
      "kind": "local",
      "path": "/root/.openclaw/workspace/config/mcporter.json"
    },
    "definition": {
      "name": "dingtalk-docs",
      "description": "dingtalk-mcp-4fd7808438dcd2709bc28c6ce2c6ac811b94b48a2674dbe6e077910f4399b1cb",
      "command": {
        "kind": "http",
        "url": "https://mcp-gw.dingtalk.com/server/4fd7808438dcd2709bc28c6ce2c6ac811b94b48a2674dbe6e077910f4399b1cb?key=fa8500322e305000e73af7b9b3768eba",
        "headers": {
          "accept": "application/json, text/event-stream"
        }
      }
    }
  },
  "artifact": {
    "path": "",
    "kind": "template"
  },
  "invocation": {
    "serverRef": "dingtalk-docs",
    "configPath": "/root/.openclaw/workspace/config/mcporter.json",
    "runtime": "node",
    "bundler": "rolldown",
    "timeoutMs": 30000,
    "minify": false
  }
} as const;
const artifactKind = determineArtifactKind();
const program = new Command();
program.name(embeddedName);
program.description(embeddedDescription);
program.option('-t, --timeout <ms>', 'Call timeout in milliseconds', (value) => parseInt(value, 10), 30000);
program.option('-o, --output <format>', 'Output format: text|markdown|json|raw', 'text');
const commandSignatures: Record<string, string> = {
  "list-accessible-documents": "function list_accessible_documents(keyword?: string);",
  "get-document-content-by-url": "function get_document_content_by_url(docUrl?: string, dentryUuid?: string);",
  "get-my-docs-root-dentry-uuid": "function get_my_docs_root_dentry_uuid();",
  "write-content-to-document": "function write_content_to_document(content: string, updateType: number, targetDentryUuid: string);",
  "create-doc-under-node": "function create_doc_under_node(name: string, parentDentryUuid: string);",
  "create-dentry-under-node": "function create_dentry_under_node(name: string, accessType: string, parentDentryUuid: string);"
};
program.configureHelp({
	commandTerm(cmd) {
		const term = cmd.name();
		return commandSignatures[term] ?? cmd.name();
	},
});
program.showSuggestionAfterError(true);

program
	.command("list-accessible-documents")
	.summary("list-accessible-documents [--keyword <keyword>] [--raw <json>]")
	.description("根据关键词，查询员工有权限访问的所有文档列表，返回文档uuid、文档标题、类型和最后更新时间。")
	.usage("[--keyword <keyword>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--keyword <keyword>", "keyword")
	
	.alias("list_accessible_documents")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.keyword !== undefined) args.keyword = cmdOpts.keyword;
			const call = (proxy.listAccessibleDocuments as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call dingtalk-docs.list_accessible_documents()");

program
	.command("get-document-content-by-url")
	.summary("get-document-content-by-url [--doc-url <doc-url>] [--dentry-uuid <dentry-uuid>] [--raw <json>]")
	.description("根据钉钉文档链接（docUrl）或文档ID（dentryUuid）获取文档内容，并以 Markdown 返回。目前仅支持钉钉在线文档。文档链接：https://alidocs.dingtalk.com/i/nodes/{dentryUuid}。dentryUuid 为32位字母数字串。仅限用户对文档具备“下载权限”时可获取，不支持跨组织查询。docUrl 与 dentryUuid 二选一必填")
	.usage("[--doc-url <doc-url>] [--dentry-uuid <dentry-uuid>] [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.option("--doc-url <doc-url>", "用于定位目标文档的钉钉文档访问链接。与 dentryUuid 二选一必填。 格式：https://alidocs.dingtalk.com/i/nodes/{dentryUuid} 或 https://docs.dingtalk.com/i/nodes/{dentryUuid}")
	.option("--dentry-uuid <dentry-uuid>", "文档的唯一标识，用于定位目标文档。与 docUrl 二选一必填。 规则：32 位字母数字字符串 可用于拼接生成链接：https://alidocs.dingtalk.com/i/nodes/{dentryUuid} (example: example-id)")
	
	.alias("get_document_content_by_url")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.docUrl !== undefined) args.docUrl = cmdOpts.docUrl;
		if (cmdOpts.dentryUuid !== undefined) args.dentryUuid = cmdOpts.dentryUuid;
			const call = (proxy.getDocumentContentByUrl as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call dingtalk-docs.get_document_content_by_url(dentryUuid: \"examp, ...)");

program
	.command("get-my-docs-root-dentry-uuid")
	.summary("get-my-docs-root-dentry-uuid [--raw <json>]")
	.description("获取当前用户“我的文档”空间的根目录节点 ID（rootDentryUuid），该 ID 可作为父节点用于创建新文档或文件夹。返回结果为一个唯一的字符串标识，仅限用户本人访问，适用于初始化文档操作、构建个人文档树等场景")
	.usage("[--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	
	.alias("get_my_docs_root_dentry_uuid")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			
			const call = (proxy.getMyDocsRootDentryUuid as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call dingtalk-docs.get_my_docs_root_dentry_uuid()");

program
	.command("write-content-to-document")
	.summary("write-content-to-document --content <content> --update-type <update-type:number> --target-dentry-uuid <target-dentry-uuid> [--raw <json>]")
	.description("将指定文本内容写入目标文档，支持两种模式：覆盖写入（清空原文档内容后写入）或续写（在文档末尾新增段落）。需提供文档唯一标识（文档ID）和写入模式。操作受文档权限控制，仅当调用者拥有编辑权限时生效。适用于自动化报告生成、日志记录、协作内容更新等场景。")
	.usage("--content <content> --update-type <update-type:number> --target-dentry-uuid <target-dentry-uuid> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--content <content>", "要写入的内容，支持markdown格式")
	.requiredOption("--update-type <update-type:number>", "0表示完全覆盖已有内容；1表示新增段落续写 (example: 1)", (value) => parseFloat(value))
	.requiredOption("--target-dentry-uuid <target-dentry-uuid>", "目标文档的唯一id。一般为dentryUuid (example: example-id)")
	
	.alias("write_content_to_document")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.content !== undefined) args.content = cmdOpts.content;
		if (cmdOpts.updateType !== undefined) args.updateType = cmdOpts.updateType;
		if (cmdOpts.targetDentryUuid !== undefined) args.targetDentryUuid = cmdOpts.targetDentryUuid;
			const call = (proxy.writeContentToDocument as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call dingtalk-docs.write_content_to_document(content: \"value\", up, ...)");

program
	.command("create-doc-under-node")
	.summary("create-doc-under-node --name <name> --parent-dentry-uuid <parent-dentry-uuid> [--raw <json>]")
	.description("在指定父节点（通过 dentryUuid 标识，如文件夹、文档、或“我的文档”根目录）下创建一篇新的在线文档，需提供文档名称。成功后返回新文档的详细信息，包括文档 ID（dentryUuid）、标题、创建时间、访问链接等。操作受权限控制，仅当调用者对父节点有写入权限时可成功创建。")
	.usage("--name <name> --parent-dentry-uuid <parent-dentry-uuid> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--name <name>", "需要创建的文档名称")
	.requiredOption("--parent-dentry-uuid <parent-dentry-uuid>", "需要创建的父节点ID。可使用 dentryUuid /docId（如来自创建文档、搜索有权限文档等操作的结果） (example: example-id)")
	
	.alias("create_doc_under_node")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.name !== undefined) args.name = cmdOpts.name;
		if (cmdOpts.parentDentryUuid !== undefined) args.parentDentryUuid = cmdOpts.parentDentryUuid;
			const call = (proxy.createDocUnderNode as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call dingtalk-docs.create_doc_under_node(name: \"value\", parentDen, ...)");

program
	.command("create-dentry-under-node")
	.summary("create-dentry-under-node --name <name> --access-type <access-type> --parent-dentry-uuid <parent-dentry-uuid> [--raw <json>]")
	.description("在指定钉钉文档节点下，创建新节点，新增的节点类型有文件夹、PDF、PPT、图片、视频、多维表、脑图、白板、表格、文档")
	.usage("--name <name> --access-type <access-type> --parent-dentry-uuid <parent-dentry-uuid> [--raw <json>]")
	.option('--raw <json>', 'Provide raw JSON arguments to the tool, bypassing flag parsing.')

	.requiredOption("--name <name>", "文件夹名称")
	.requiredOption("--access-type <access-type>", "新增的节点类型，枚举类型：0:文档；1:表格；2:PPT；3:白板；6:脑图；7:多维表；9:视频；10:图片；13:文件夹；14:PDF；99:其他文件")
	.requiredOption("--parent-dentry-uuid <parent-dentry-uuid>", "父节点ID (example: example-id)")
	
	.alias("create_dentry_under_node")	.action(async (cmdOpts) => {
		const globalOptions = program.opts();
		const runtime = await ensureRuntime();
		const serverName = embeddedName;
		const proxy = createServerProxy(runtime, serverName, {
			initialSchemas: embeddedSchemas,
		});
		try {
			const args = cmdOpts.raw ? JSON.parse(cmdOpts.raw) : ({} as Record<string, unknown>);
			if (cmdOpts.name !== undefined) args.name = cmdOpts.name;
		if (cmdOpts.accessType !== undefined) args.accessType = cmdOpts.accessType;
		if (cmdOpts.parentDentryUuid !== undefined) args.parentDentryUuid = cmdOpts.parentDentryUuid;
			const call = (proxy.createDentryUnderNode as any)(args);
			const result = await invokeWithTimeout(call, globalOptions.timeout || 30000);
			printResult(result, globalOptions.output ?? 'text');
		} finally {
			await runtime.close(serverName).catch(() => {});
		}
	})
	.addHelpText('after', () => '\nExample:\n  ' + "mcporter call dingtalk-docs.create_dentry_under_node(name: \"value\", access, ...)");

program
	.command('__mcporter_inspect', { hidden: true })
	.description('Internal metadata printer for mcporter inspect-cli.')
	.action(() => {
		const payload = buildMetadataPayload();
		console.log(JSON.stringify(payload, null, 2));
	});

configureToolCommandHelps();

const FORCE_COLOR = process.env.FORCE_COLOR?.toLowerCase();
const forceDisableColor = FORCE_COLOR === '0' || FORCE_COLOR === 'false';
const forceEnableColor = FORCE_COLOR === '1' || FORCE_COLOR === 'true' || FORCE_COLOR === '2' || FORCE_COLOR === '3';
const hasNoColor = process.env.NO_COLOR !== undefined;
const stdoutStream = process.stdout as NodeJS.WriteStream | undefined;
const supportsAnsiColor = !hasNoColor && (forceEnableColor || (!forceDisableColor && Boolean(stdoutStream?.isTTY)));

const tint = {
	bold(text: string): string {
		return supportsAnsiColor ? '[1m' + text + '[0m' : text;
	},
	dim(text: string): string {
		return supportsAnsiColor ? '[90m' + text + '[0m' : text;
	},
	extraDim(text: string): string {
		return supportsAnsiColor ? '[38;5;244m' + text + '[0m' : text;
	},
};

function configureGeneratedCommandHelp(command: Command): void {
	command.configureHelp({
		commandUsage(target) {
			const usage = (target.name() + ' ' + target.usage()).trim() || target.name();
			return supportsAnsiColor ? tint.bold(usage) : usage;
		},
		optionTerm(option) {
			const term = option.flags ?? '';
			return supportsAnsiColor ? tint.bold(term) : term;
		},
		optionDescription(option) {
			const description = option.description ?? '';
			return supportsAnsiColor ? tint.extraDim(description) : description;
		},
	});
}

function configureToolCommandHelps(): void {
	program.commands.forEach((cmd) => {
		if (cmd.name() === '__mcporter_inspect') {
			return;
		}
		configureGeneratedCommandHelp(cmd);
	});
}

function renderStandaloneHelp(): string {
	const colorfulTitle = tint.bold(embeddedName) + ' ' + tint.dim('— ' + embeddedDescription);
	const plainTitle = embeddedName + ' — ' + embeddedDescription;
	const title = supportsAnsiColor ? colorfulTitle : plainTitle;
	const lines = [title, '', 'Usage: ' + embeddedName + ' <command> [options]', ''];
	if (generatorTools) {
		lines.push(formatEmbeddedTools());
	}
	lines.push('', formatGlobalFlags(), '', formatQuickStart());
	if (generatorInfo) {
		lines.push('', tint.extraDim(generatorInfo));
	}
	return lines.join('\n');
}

program.helpInformation = () => renderStandaloneHelp();

function formatEmbeddedTools(): string {
	const header = supportsAnsiColor ? tint.bold('Embedded tools') : 'Embedded tools';
	if (!generatorTools.length) {
		return header;
	}
	const lines = [header];
	generatorTools.forEach((entry) => {
		const renderedDesc = entry.description
			? supportsAnsiColor
				? tint.extraDim(entry.description)
				: entry.description
			: undefined;
		const base = renderedDesc ? entry.name + ' - ' + renderedDesc : entry.name;
		lines.push('  ' + base);
		if (entry.flags) {
			const renderedFlags = supportsAnsiColor ? tint.extraDim(entry.flags) : entry.flags;
			lines.push('    ' + renderedFlags);
		}
		lines.push('');
	});
	if (lines[lines.length - 1] === '') {
		lines.pop();
	}
	return lines.join('\n');
}

function formatGlobalFlags(): string {
	const header = supportsAnsiColor ? tint.bold('Global flags') : 'Global flags';
	const entries = [
		['-t, --timeout <ms>', 'Call timeout in milliseconds'],
		['-o, --output <format>', 'text | markdown | json | raw (default text)'],
	];
	const formatted = entries.map(([flag, summary]) => '  ' + flag.padEnd(28) + summary);
	return [header, ...formatted].join('\n');
}

function formatQuickStart(): string {
  const header = supportsAnsiColor ? tint.bold('Quick start') : 'Quick start';
  const examples = quickStartExamples();
  if (!examples.length) {
    return header;
  }
  const formatted = examples.map(([cmd, note]) => '  ' + cmd + '\n    ' + tint.dim('# ' + note));
  return [header, ...formatted].join('\n');
}

function quickStartExamples(): Array<[string, string]> {
  const examples: Array<[string, string]> = [];
  const commandMap = new Map<string, string>();
  program.commands.forEach((cmd) => {
    const name = cmd.name();
    if (name !== '__mcporter_inspect') {
      commandMap.set(name, name);
    }
  });
  const embedded = Array.isArray(generatorTools) ? generatorTools : [];
  for (const entry of embedded.slice(0, 3)) {
    const commandName = commandMap.get(entry.name) ?? entry.name;
    const flags = entry.flags ? ' ' + entry.flags.replace(/<[^>]+>/g, '<value>') : '';
    examples.push([embeddedName + ' ' + commandName + flags, 'invoke ' + commandName]);
  }
  if (!examples.length) {
    examples.push([embeddedName + ' <tool> --key value', 'invoke a tool with flags']);
  }
  return examples;
}

function printResult(result: unknown, format: string) {
	const wrapped = createCallResult(result);
	switch (format) {
		case 'json': {
			const json = wrapped.json();
			if (json) {
				console.log(JSON.stringify(json, null, 2));
				return;
			}
			break;
		}
		case 'markdown': {
			const markdown = wrapped.markdown();
			if (markdown) {
				console.log(markdown);
				return;
			}
			break;
		}
		case 'raw': {
			console.log(JSON.stringify(wrapped.raw, null, 2));
			return;
		}
	}
	const text = wrapped.text();
	if (text) {
		console.log(text);
	} else {
		console.log(JSON.stringify(wrapped.raw, null, 2));
	}
}

function normalizeEmbeddedServer(server: typeof embeddedServer) {
	const base = { ...server } as Record<string, unknown>;
	if ((server.command as any).kind === 'http') {
		const urlRaw = (server.command as any).url;
		const urlValue = typeof urlRaw === 'string' ? urlRaw : String(urlRaw);
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				url: new URL(urlValue),
			},
		};
	}
	if ((server.command as any).kind === 'stdio') {
		return {
			...base,
			command: {
				...(server.command as Record<string, unknown>),
				args: [ ...((server.command as any).args ?? []) ],
			},
		};
	}
	return base;
}

function determineArtifactKind(): 'template' | 'bundle' | 'binary' {
	const scriptPath = typeof process !== 'undefined' && Array.isArray(process.argv) ? process.argv[1] ?? '' : '';
	if (scriptPath.endsWith('.ts')) {
		return 'template';
	}
	if (scriptPath.endsWith('.js')) {
		return 'bundle';
	}
	return 'binary';
}

function resolveArtifactPath(): string {
	if (typeof process !== 'undefined' && Array.isArray(process.argv) && process.argv.length > 1) {
		const script = process.argv[1];
		if (script) {
			return script;
		}
	}
	return embeddedMetadata.artifact.path;
}

function buildMetadataPayload() {
	const invocation = { ...embeddedMetadata.invocation };
	const path = resolveArtifactPath();
	if (artifactKind === 'template' && path) {
		invocation.outputPath = invocation.outputPath ?? path;
	} else if (artifactKind === 'bundle' && path) {
		invocation.bundle = invocation.bundle ?? path;
	} else if (artifactKind === 'binary' && path) {
		invocation.compile = invocation.compile ?? path;
	}
	return {
		...embeddedMetadata,
		artifact: {
			path,
			kind: artifactKind,
		},
		invocation,
	};
}

async function ensureRuntime(): Promise<Awaited<ReturnType<typeof createRuntime>>> {
	return await createRuntime({
		servers: [normalizeEmbeddedServer(embeddedServer)],
	});
}

async function invokeWithTimeout<T>(call: Promise<T>, timeout: number): Promise<T> {
	if (!Number.isFinite(timeout) || timeout <= 0) {
		return await call;
	}
	let timer: ReturnType<typeof setTimeout> | undefined;
	try {
		return await Promise.race([
			call,
			new Promise<never>((_, reject) => {
				timer = setTimeout(() => {
					reject(new Error('Call timed out after ' + timeout + 'ms.'));
				}, timeout);
			}),
		]);
	} finally {
		if (timer) {
			clearTimeout(timer);
		}
	}
}

async function runCli(): Promise<void> {
	const args = process.argv.slice(2);
	if (args.length === 0) {
		program.outputHelp();
		return;
	}
	await program.parseAsync(process.argv);
}

if (process.env.MCPORTER_DISABLE_AUTORUN !== '1') {
	runCli().catch((error) => {
		const message = error instanceof Error ? error.message : String(error);
		console.error(message);
		process.exit(1);
	});
}
